import { Html, Head, Main, NextScript } from 'next/document'
import Navigation from '@/components/navigation'

export default function Document({ authorization }) {
  return (
    <Html lang="en">
      <Head>
        <title>Dealer Gears</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" 
            rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossOrigin="anonymous" />
      </Head>
      <body>
        <Navigation authorization={ authorization } />
        <main className="container">
          <div className="row-fluid">
              <div className="table-responsive">
                <Main />
              </div>
            </div>
          </main>
          <NextScript />
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
      </body>
    </Html>
  )
}
